/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['id.js']) {
  _$jscoverage['id.js'] = [];
  _$jscoverage['id.js'][1] = 0;
  _$jscoverage['id.js'][22] = 0;
  _$jscoverage['id.js'][23] = 0;
  _$jscoverage['id.js'][25] = 0;
  _$jscoverage['id.js'][26] = 0;
  _$jscoverage['id.js'][29] = 0;
}
_$jscoverage['id.js'][1]++;
var ids = {};
_$jscoverage['id.js'][22]++;
module.exports = (function (p) {
  _$jscoverage['id.js'][23]++;
  var prefix = p === undefined? "luc-": p;
  _$jscoverage['id.js'][25]++;
  if (ids[prefix] === undefined) {
    _$jscoverage['id.js'][26]++;
    ids[prefix] = 0;
  }
  _$jscoverage['id.js'][29]++;
  return prefix + ids[prefix]++;
});
_$jscoverage['id.js'].source = ["var ids = {};","/**"," * @member Luc"," * @method id"," * "," * Return a unique id."," * @param {String} [prefix] Optional prefix to use"," *"," *","        Luc.id()","        &gt;\"luc-0\"","        Luc.id()","        &gt;\"luc-1\"","        Luc.id('my-prefix')","        &gt;\"my-prefix0\"","        Luc.id('')","        &gt;\"0\""," *"," * @return {String}"," *"," */","module.exports = function(p) {","    var prefix = p === undefined ? 'luc-' : p;","","    if(ids[prefix] === undefined) {","        ids[prefix] = 0;","    }","","    return prefix + ids[prefix]++;","};"];
