/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['events/eventEmitter.js']) {
  _$jscoverage['events/eventEmitter.js'] = [];
  _$jscoverage['events/eventEmitter.js'][1] = 0;
  _$jscoverage['events/eventEmitter.js'][13] = 0;
  _$jscoverage['events/eventEmitter.js'][15] = 0;
  _$jscoverage['events/eventEmitter.js'][17] = 0;
  _$jscoverage['events/eventEmitter.js'][18] = 0;
  _$jscoverage['events/eventEmitter.js'][21] = 0;
  _$jscoverage['events/eventEmitter.js'][23] = 0;
  _$jscoverage['events/eventEmitter.js'][26] = 0;
}
_$jscoverage['events/eventEmitter.js'][1]++;
var EventEmitter = require("events").EventEmitter;
_$jscoverage['events/eventEmitter.js'][13]++;
EventEmitter.prototype.once = (function (type, listener) {
  _$jscoverage['events/eventEmitter.js'][15]++;
  var self = this, g = (function () {
  _$jscoverage['events/eventEmitter.js'][17]++;
  self.removeListener(type, g);
  _$jscoverage['events/eventEmitter.js'][18]++;
  listener.apply(this, arguments);
});
  _$jscoverage['events/eventEmitter.js'][21]++;
  self.on(type, g);
  _$jscoverage['events/eventEmitter.js'][23]++;
  return this;
});
_$jscoverage['events/eventEmitter.js'][26]++;
module.exports = EventEmitter;
_$jscoverage['events/eventEmitter.js'].source = ["var EventEmitter = require('events').EventEmitter;","/**"," * @license https://raw.github.com/joyent/node/v0.10.11/LICENSE"," * Node js license. EventEmitter will be in the client"," * only code."," */","/**"," * @class Luc.EventEmitter"," * The wonderful event emmiter that comes with node,"," * that works in the supported browsers."," * [http://nodejs.org/api/events.html](http://nodejs.org/api/events.html)"," */","EventEmitter.prototype.once = function(type, listener) {","    //put in fix for IE 9 and below","    var self = this,","        g = function() {","            self.removeListener(type, g);","            listener.apply(this, arguments);","        };","","    self.on(type, g);","","    return this;","};","","module.exports = EventEmitter;"];
